middleman/middlemanapp.com

- Gemfile
- source/layouts/layout.erb
Also added necessary gems for Windows testing
Closes #396
> Update copyright year

- data/sites.yml
ref: http://dojo4.com/blog/static-is-the-new-black
> Add http://dojo4.com to sites.yml

- source/stylesheets/modules/_global-nav.scss
Looks like this was actually just a typo, everything lines up now
Closes #403
> Bump .logo-text font size

- data/sites.yml
Adding our site to the *Sites Built Using Middleman* index.
> Add our website

- data/sites.yml
> Added 3 middleman sites to the list

- data/sites.yml
> eventxtra added

- data/sites.yml
> [sites] Add CocoaPods

- data/sites.yml
- source/sitemap.xml.builder
Sitemap should match the urls that are linked internally.
> Don't include index.html in sitemap, and update sites.yml

- data/sites.yml
> Updated sites.yml

- config.rb
Re: https://github.com/middleman/middleman/pull/1467
I don't know what your preference is for single quotes vs double quotes, let me know so I choose correctly in future. =]
> Add dynamic-pages redirect

- data/sites.yml
- source/basics/build_and_deploy.html.markdown
Hi there,
I added my own site to the `site.yaml` and also extended the section about "Build and Deploy". Hope it's ok to do this in one PR.
Cheers
/mm
> Add site and add infos to build_and_deploy

- data/sites.yml
Added Create the Bridge and 26 Gems to the Built List.
> Updates to sites.yml

- data/sites.yml
http://ikuwow.website
https://github.com/ikuwow/query_ok
> Add Query OK (ikuwow's blog) to the blog list using middleman

- data/sites.yml
New site powered by middleman.
> Add link to vyber-tydne.kle.cz

- data/sites.yml
> Add mizukiabe.net to sites.yml

- source/basics/blogging.html.markdown
> Fix link to nested layouts

- data/sites.yml
Just finished a new blog at this address. Loved using Middleman for it!
> Add www.downrightlies.net to the blogs section of the sites page

- data/sites.yml
This has a title, so is hopefully OK. Improved version of https://github.com/middleman/middleman-guides/pull/464
> Add www.downrightlies.net to the blogs section of the sites page with a title

- data/sites.yml
> Added Smartcoin website info

- source/advanced/custom_extensions.html.markdown
- source/advanced/pretty_urls.html.markdown
- source/basics/blogging.html.markdown
> Broken links fixes

- Gemfile
- source/javascripts/site.js
This adds deep anchors using anchor.js. I used the default settings.
Relates to #472
> Added anchor.js

- Gemfile
- source/javascripts/site.js
Addresses https://github.com/middleman/middleman-guides/issues/475.
> Anchor placement

- data/sites.yml
> add: Lauren Dorman's site to sites built using Middleman

- data/sites.yml
Middleman showcase of a style guide and prototype
> Add Greenpeace Greenwire to sites.yml

- data/sites.yml
I had a great experience creating my portfolio site with Middleman!
> Add nickholden.io to sites made with Middleman

- data/sites.yml
Hey there!
Was reading the documentation and saw the [list of sites built with middleman](https://middlemanapp.com/community/built_using_middleman/), along with a call to submit this PR. So here it is!
Thanks again for this great project :smile_cat:
> Adds ashfurrow.com to built sites.

- source/basics/development_cycle.html.markdown
> Mention LiveReload gem

- source/basics/upgrade-v4.html.markdown
Editor also removed tabs from blank lines. Was unable to update the japanese version.
> :arrow_up: current beta to `v4.0.0.beta.2`

- source/stylesheets/modules/_built-with-middleman.scss
Closes #509 
Not perfect, but keeps proper layout at all sizes at least
Travis failure unrelated
> Wrap "built with middleman" links

- source/basics/development_cycle.html.markdown
Add a note about reloading CSS partials
> Update LiveReload section

- data/sites.yml
> Add sistrall.it to sites.yml

- source/stylesheets/modules/_footer.scss
https://github.com/middleman/middleman-guides/pull/458#issuecomment-143800985
> Replace `inline-image` with `url` in CSS rule

- data/sites.yml
> Add Met Kock to sites.yml

- source/basics/directory-structure.html.markdown
Hi,
in the example mymiddlemansite is the main Middleman directory, isn't it?
And source, build, data and lib are sub-directories of it, aren't they?
> guide directory structure: siblings => children

- source/basics/development_cycle.html.markdown
depends on https://github.com/wazeHQ/middleman-livereload/commit/566151c1b661a7192dc42bccfbd6e779cdac2fe8
> Update Reloading CSS section

- source/basics/start_new_site.html.markdown
Hi,
please consider adding this example to the description of middleman init
> Starting a New Site guide: added example middleman init without parameter

- data/sites.yml
This adds [Bodypil Zuckerpaste](https://www.bodypil.de/) to [the sites](https://middlemanapp.com/community/built_using_middleman/). Probably the most beautiful site on the internet. And the fastest one. Built using middleman, served via S3+CloudFront (`middleman-s3_sync`, `middleman-cloudfront`), some custom javascript to make stuff really fast, includes a blog (`middleman-blog`) and so on.
> Add bodypil.de to sites

- data/sites.yml
I'd love to see our site listed as an example built w/ middleman.
> Link to our website, built using middleman

- data/sites.yml
Added JoshLain.cz to sites list.
> Adding my site to sites list

- source/basics/partials.html.markdown
Updated link to partial helper info on redesigned Padrino site
> fix Padrino helpers link

- data/sites.yml
ManageIQ site is built using Middleman
> Add ManageIQ to sites.yml

- data/sites.yml
Hi,
I added my blog built with Middleman Blog.
- URL: http://ngs.io
- Source: https://github.com/ngs/sources.ngs.io
Thanks
> Add ngs.io

- source/advanced/dynamic_pages.html.markdown
Added some guidance for using dynamic pages with directory indexes as it wasn't immediately clear how to do this when I was looking through documentation. Thanks :)
> Added info about combining with Directory Indexes

- source/advanced/dynamic_pages.html.markdown
Hi there.  Unfortunately I forgot to add a blank line when adding my changes before.  Hopefully this should make it look better in the guide.  Thanks
> Fixed formatting of previous commit

- data/sites.yml
Hi, I added my website [erickuhn19.com](http://erickuhn19.com) to the website list. It's built with Middleman, you can find the source code [here](https://github.com/erickuhn19/erickuhn19.github.io).
> added erickuhn19.com to blogs built with middleman

- data/sites.yml
Add my blog detail into sites.yml
> Add my blog detail into sites.yml

- source/localizable/advanced/sitemap.jp.html.markdown
> Remove reference to deprecated query interface in JP

- source/basics/helper_methods.html.markdown
- source/localizable/basics/helper_methods.jp.html.markdown
The example could cause confusion for a newbie... like myself... which it did.  Hopefully this will make it a little easier for the next newbie.
> add missing equal sign so the partial will render

- data/sites.yml
One blog and one podcast site (mostly blog atm) built proudly with Middleman :)
> Add links to opensourcery.co.za & zadevchat.io

- source/localizable/basics/blogging.jp.html.markdown
> Update blogging to include current version of gem in JP

- data/sites.yml
We're big fans of Middleman. Thanks for all the work put into it!
> Add DigitalOcean to built sites

- source/advanced/external-pipeline.html.markdown
We're using something like this for our middleman site, and it works well.
(this is a boiled-down example, but should be a good start)
> Broccoli example

- source/localizable/advanced/external-pipeline.jp.html.markdown
> Add Broccoli example in JP

- data/sites.yml
- Add missing title for Archiver
- Add Renamer to list
> Update sites built with Middleman

- data/sites.yml
- Ruby Nord - A Ruby User Group from the North of France
- Nomad Rides - A remote workers community that travels a bit
- and myself :)
Yep, I ❤️ middleman, middleman everywhere! :)
> Add Ruby Nord, Nomad Rides and myself to list of sites

- data/sites.yml
> Add PRX.co to Middleman-powered sites

- source/localizable/basics/upgrade-v4.html.markdown
Make indentation consistent (2 spaces) in source creation section.
> Fix indentation

- .travis.yml
- config.rb
- locales/jp.yml
- source/localizable/basics/start-new-site.jp.html.markdown
- update docs in JP.
- fixed.
- Sidebar is not displayed in JP docs.
- Top page is broken in JP docs.
- node problem (too old version).
> Update JP docs in 2017-03-07

- source/localizable/advanced/asset-pipeline.html.markdown
- source/localizable/advanced/custom-extensions.html.markdown
- source/localizable/advanced/dynamic-pages.html.markdown
- source/localizable/advanced/external-pipeline.html.markdown
- source/localizable/advanced/file-size-optimization.html.markdown
- source/localizable/advanced/improving-cacheability.html.markdown
- source/localizable/advanced/localization.html.markdown
- source/localizable/advanced/pretty-urls.html.markdown
- source/localizable/advanced/project-templates.html.markdown
- source/localizable/advanced/rack-middleware.html.markdown
- source/localizable/advanced/sitemap.html.markdown
- Wrap lines at 80 characters.
- Use reference-style links.
> Markdown style

- source/localizable/advanced/localization.html.markdown
it is maybe more straight forward for newcommers like this.
> feat: directory tree

- source/localizable/basics/template-engine-options.html.markdown
- source/localizable/basics/template-engine-options.jp.html.markdown
* https://github.com/haml/haml/pull/894
> Remove unsupported `:ugly` haml option.

- source/localizable/advanced/localization.html.markdown
- source/localizable/advanced/localization.jp.html.markdown
- fix line break in en.
- update translattion in jp.
- related #698
> Add directory tree in JP.

- source/localizable/basics/build-and-deploy.jp.html.markdown
> how to disable contracts in jp

- data/sites.yml
since we proudly use middleman \o/
> Added StormForger to sites.yml

- source/localizable/basics/redirects.jp.html.markdown
> specify where to apply redirects in JP

- source/localizable/advanced/data-files.html.markdown
- source/localizable/advanced/pretty-urls.html.markdown
- source/localizable/advanced/project-templates.html.markdown
- source/localizable/advanced/sitemap.html.markdown
- source/localizable/basics/blogging.html.markdown
- source/localizable/basics/build-and-deploy.html.markdown
- source/localizable/basics/frontmatter.html.markdown
- source/localizable/basics/helper-methods.html.markdown
- source/localizable/basics/install.html.markdown
- source/localizable/basics/layouts.html.markdown
- source/localizable/basics/partials.html.markdown
- source/localizable/basics/start-new-site.html.markdown
Hey! I love what you guys are doing with Middleman, definitely an awesome framework. I created some video tutorials teaching core concepts on the docs. I think it could be a big help to new users trying to learn the framework!
Here's a link to the full playlist on youtube : 
https://www.youtube.com/playlist?list=PLLAZ4kZ9dFpMmiuoOACWHVxBk6VjqSLRr
> Added several tutorial videos to relevant docs pages

- source/localizable/advanced/file-size-optimization.jp.html.markdown
> Update file-size-optimization.html.markdown in JP

- data/sites.yml
I added them to the top for convenience. I hope the theme orders them in some way.
> Add sites I built in Middleman

- data/sites.yml
Loving Middleman more and more everyday! Just launched a new side project and wanted to add it to your list here.
> Update sites with css gradient

- data/sites.yml
This is for the site https://mikerogers.io/ which is mine, so I've also
included the source code :)
> Adding MikeRogers.io to sites list

- data/sites.yml
Just adding my site to the sites using Middleman section. Absolutely love Middleman, keep up the great work!
> Adding my site to the sites.yml file

- data/sites.yml
My site is no longer built using Middleman.
> Remove reference

- data/sites.yml
Added URL https://apps.inspira.io to the list of sites built with middleman.
> Updated sites data list

- data/sites.yml
> Add endpoint.com site created with Middleman

- source/localizable/basics/development-cycle.jp.html.markdown
- source/localizable/basics/helper-methods.jp.html.markdown
> Japanese Update: 2020-12-30

- source/localizable/advanced/custom-extensions.html.markdown
I was looking for the complete list of callbacks available to me and couldn't find them. The docs suggest people go find them on their own, but I thought it might be nice to at least include a list. Happy to flesh these out more with examples. I only used one of them, so I don't know enough about what examples might look like. 
Thanks for your consideration!
> add a list of additional callbacks and where they get called

- source/localizable/advanced/custom-extensions.jp.html.markdown
- source/localizable/basics/redirects.jp.html.markdown
This PR adds the Japanese version of the PR that has already been merged.
- #854
- #931
By the way, I changed my account name from `yterajima` to my real name `yuya-matsushima` for work reasons.
I will continue to update the Japanese documentation periodically.
> Japanese Update: 2021-11-08

- data/sites.yml
No longer built with Middleman (and moved to endpointdev.com).
> Remove defunct site
