Gemfile
source/stylesheets/base/_typography.scss

Currently every code block has scrollbars (for me on chrome/firefox at least), this patch makes them appear only when needed.
Also added some stuff to the `Gemfile` to silence warnings on Windows.

Fix unnecessary scrollbars

---

data/sites.yml

I added the full title for the site turing.cool.

Update title for Turing Incomplete

---

source/advanced/custom_extensions.html.markdown

I added a section about bootstrapping an extension.

Add hint for `extension`-helper

---

source/localizable/_footer.html.erb
source/stylesheets/modules/_footer.scss

Make it more obvious that we're available for hire.
Looks like this:
What do you think?

Add link to thoughtbot from footer image

---

README.md

old link was throwing an SSL warning in Chrome.

update donate link in readme

---

data/sites.yml
source/localizable/community.html.erb

Updating the deployment extensions link to point to the correct tag.
I've also added two recent sites built using middleman to the list.

Update deployment extensions link and add sites to community list

---

source/stylesheets/base/_typography.scss
source/stylesheets/base/_variables.scss
source/stylesheets/modules/_documentation-nav.scss

It's kinda hard to read the current documentation due to low contrast, especially on non-Retina/crappy screens.
This PR is my attempt at increasing the contrast while keeping the main colors as much the same as possible. The W3C recommends a [minimum contrast ratio](http://www.w3.org/TR/WCAG/#visual-audio-contrast-contrast) of 4.5:1, which I think is still violated in some places even after these changes (e.g. comments in code sections) but at least not in the main text.
I think the [white on yellow](https://leaverou.github.io/contrast-ratio/#white-on-%23f3c859) nav bar at the top is also not great in terms of contrast, but I thought changing that might be a bit much.

Increase text color contrast for readability

---

data/sites.yml

Unfortunately, middleman is no longer used for this website.

Remove outdated site link

---

data/sites.yml

[saltstack.cz](https://saltstack.cz) is powered by Middleman

saltstack.cz

---

source/stylesheets/modules/_documentation-nav.scss

fixes issue with firefox clipping text in the input field [close #501]. looks like things are a little more consistent in IE as well (though I'll admit I only check on IE 10)

use height instead of padding for documentation search field

---

source/advanced/file_size_optimization.html.markdown

* example as is throws error
* corrected per gh issue 500 with prefixing with :: -> https://github.com/middleman/middleman/issues/900#issuecomment-51356664
* other possible fix, update example with :: namespace resolution operator so it works without any changes
* uglifier is a dependency of middleman gem, so removed block to include it: https://rubygems.org/gems/middleman/versions/3.4.0

clarified example

---

source/basics/blogging.html.markdown

- Group the Pretty URLs directions for blogging at one specific section. 
- Update the note that warns the user about activating the `directory_indexes` **after** the `middleman-blog` activation (make it more direct)

Update Pretty URLs copy on the "Blogging" guide section

---

source/stylesheets/modules/_footer.scss

The url was linking to the wrong place.

Fix FormKeep logo not showing up

---

data/sites.yml

Built by Middleman and Behance API. Hosted on GitHub:
http://www.krivoydesigner.com/
Source: https://github.com/nostrism/nostrism.github.io/tree/middleman

Add item to «Sites Built Using Middleman»

---

source/stylesheets/modules/_footer.scss

How it looks in Firefox right before:
... and after.

Fix stretched FormKeep logo in Firefox

---

source/basics/start_new_site.html.markdown
source/localizable/basics/start_new_site.jp.html.markdown

`require 'rubygems'` is already required in Ruby 1.9 or later.

remove unnecessary require

---

source/basics/upgrade-v4.html.markdown

Small change, [reasoning](http://www.quickanddirtytips.com/education/grammar/affect-versus-effect)

Fix typo: "effect" → "affect"

---

source/localizable/advanced/project_templates.jp.html.markdown

I found a broken link in Japanese translation.
See: https://middlemanapp.com/jp/advanced/project_templates/
I removed a needless white space.

Fix typo in project_templates.jp

---

source/basics/upgrade-v4.html.markdown

It looks like sprockets was pulled out of rc2. I updated the middleman-guide to reflect that and (hopefully) instruct the user to add `middleman-sprockets` to their Gemfile to get sprockets support back.
Is the same true for `middleman-compass`? There's still a reference to compass in the `middleman-core` rc2 build that makes this unclear.

Update for 4.0.0.rc2

---

README.md

Without `npm install` starting the server errors out as follows:
```
== External: Command failed with message: No such file or directory - ./node_modules/webpack/bin/webpack.js
```

Document need for npm in order to run the site locally

---

data/sites.yml

We released our developer blog on Middleman. Adding it correctly to the "blogs" section this time.

Add HireArt dev blog to list

---

source/basics/partials.html.markdown
source/localizable/basics/partials.jp.html.markdown

Under the `Partials` page, the link titled "Padrino Render Helpers" points to a broken link.  Updated it to point to the correct page of the Padrino docs.

Updated link to Padrino Render Helper documentation page.

---

source/basics/layouts.html.markdown
source/localizable/basics/layouts.jp.html.markdown

This fixes the ERB tag used to invoke `wrap_layout` by changing it to an output tag. The example does not work when a non-outputting execution tag is used.
This also updates the example for setting a nested blog layout by showing how to do so within the `activate :blog` block. Readers coming from the [Layouts section of the Blogging page](https://middlemanapp.com/basics/blogging/#layouts) might get confused when they see the invocation of `page` with a `:layout` option, in that they might think they need to use both approaches. This change indicates that either is possible.
Thanks for these great guides!

Fix `wrap_layout` example

---

source/advanced/configuration.html.markdown

This adds a section detailing how to access configuration settings made in `config.rb` from templates and helpers.
Thanks @tdreyno for your help clarifying this!

Add usage of `config` from templates and helpers

---

source/advanced/file_size_optimization.html.markdown

While digging deep into the bowels of the MM4 source code, I couldn't find anything referencing the `js_compressor` options in the `minify_javascript` extension. Updated the docs to reflect the use of the `compressor` option instead.

Update minify_javascript options for MM4.

---

source/advanced/sitemap.html.markdown

Let's end [the confusion](https://forum.middlemanapp.com/t/sitemap-where-causes-nomethoderror/2302).

Remove reference to deprecated query interface

---

data/sites.yml

Howdy, we just relaunched our expensive complex marketing website as a much less expensive Middleman site on S3+CloudFront+ACM. :heart: Middleman.

Add Trailpost to list of websites built using Middleman. Yay.

---

source/basics/blogging.html.markdown

As written middleman-blog defaults to version 0.1.5. Yikes!  The links to generated files are also outdated.

Update blogging to include current version of gem

---

data/sites.yml

I'm adding the Software Niagara website to the "Built with Middleman" section of the site. This site was built with Middleman 3 two years ago and just rebuilt with Middleman 4. Makes use of Middleman data, webpack, and functional css.

Add Software Niagara to sites

---

package.json

Hi, we fixed some bugs in docsearch, like displaying a "no results" screen when there are .. no results.
Could you rebuild the middleman website with that new version? Thanks!

docs(docsearch): upgrade docsearch version

---

source/basics/development_cycle.html.markdown

Haml changed their url to http://haml.info, this updates the link on the Development Cycle page.

Update broken link to Haml site

---

data/sites.yml

IC Hack is Imperial College London's annual hackathon

Add ichack.org to list of sites using middleman

---

source/layouts/layout.erb

The HTML `lang` attribute is used to identify the language of text
content on the page. Among other things, it will help screen readers
switch language profiles to provide the correct accent and
pronunciation.
See: https://www.paciellogroup.com/blog/2016/06/using-the-html-lang-attribute/

Add lang attribute to html element in layout

---

.gitignore
Gemfile.lock

This was ignored back in https://github.com/middleman/middleman-guides/commit/73dd39dddaa4d329b17ea4f20acd9792bc25e0f4 when this repo was a Middleman template.
Now that this is a full Middleman instance, it's useful to check the Gemfile.lock file into version control. More info on that on the Bundler website: http://bundler.io/v1.3/rationale.html#checking-your-code-into-version-control

Check Gemfile.lock into version control

---

.gitignore
README.md
bin/setup

This let’s contributors run one simple script (`bin/setup`) which should set their machine up, rather than a few scrips to work through.

Add a setup script

---

source/layouts/layout.erb
source/stylesheets/base/_variables.scss

By switching to system fonts we maintain a similar look and feel, while eliminating the need for loading external resources: fonts from Google.
In my opinion, San Francisco (Apple’s system font, shown below) has a more rigid feel than Lato (the currently used Google font) which I think better aligns with the structure of the Middleman logo. A win-win.
The font stack comes from https://github.com/mrmrs/css-system-fonts.
Note that Bourbon v5 will ship with a `$font-stack-system` variable, so this long list can be wrapped up simply as `font-family: $font-stack-system;` once we upgrade from v4.

Use system fonts

---

config.rb

This tells the plugin to use WebSockets instead.
See: https://github.com/middleman/middleman-livereload#configuration

Disable Flash polyfill for LiveReload

---

source/stylesheets/modules/_browser.scss

This CSS asset link was busted and causing the “fake browser bars” on the home page to not show at all:

Fix broken asset link

---

source/stylesheets/base/_variables.scss

The current yellow felt a little dull to me, so I’m trying out a deeper, more golden yellow.
(current on the left, updated on the right)

Tweak Middleman yellow color

---

source/partials/_docsearch.erb

Form elements without labels present accessibility issues.
See: https://dequeuniversity.com/rules/axe/2.1/label?application=axeChrome

Add `aria-label` to docs search

---

source/localizable/basics/start_new_site.html.markdown

- Update `config.ru` section
- Remove mention of the `--rack` CLI flag because it no longer exists.
- Simplify some wording and link to the Middleman configuration page

Documentation updates

---

locales/en.yml
locales/jp.yml
source/partials/_documentation_nav.erb

This `/advanced/custom-templates/` link redirects to
`/advanced/project_templates/`, which is already in the nav on Line 51.
The redirect is in place on Line 22 in `config.rb`.

Remove duplicate link

---

config.rb
source/netlify-redirects

Since Middleman is simply a static site generator, it's limited in how
it can handle redirects. The meta refresh tags it outputs are not
accessible or SEO-friendly, and they don't send 301 redirect headers.
Netlify, which this website is hosted on, allows us to configure
redirects server-side, which resolves all of these problems.
https://www.netlify.com/docs/redirects/
Note that Netlify needs a `_redirects` file at the root of the site, but
because Middleman ignores files that begin with an underscore, a
`_redirects` file would not be output into the built site. To get around
this, a proxy is used to rename the file from `redirects` to
`_redirects` on build.

Move redirect handling to Netlify

---

.hound.yml
.scss-lint.yml

- Hound comments on style violations in GitHub pull
requests: https://houndci.com/
- Enable SCSS linting for Hound, which leverages
SCSS-Lint: https://github.com/brigade/scss-lint
Note: Hound still needs to be enabled for this repo once/if we merge this by going to https://houndci.com/, logging in and clicking “Activate.”

Setup Hound and SCSS-Lint

---

Gemfile
Gemfile.lock
source/stylesheets/base/_grid-settings.scss
source/stylesheets/base/_variables.scss
source/stylesheets/modules/_browser.scss
source/stylesheets/modules/_community.scss
source/stylesheets/modules/landing/_community.scss
source/stylesheets/modules/landing/_donate.scss
source/stylesheets/modules/landing/_hero.scss
source/stylesheets/modules/landing/_introduction.scss

- The `size` mixin now requires a comma between two values.
- The `em` mixin has been removed; replaced instances of this with raw
`em` values.
- Use the new font stack variables.

Update to Bourbon v5.0.0

---

README.md
helpers/guide_helpers.rb
package.json
source/localizable/community/built-using-middleman.html.erb

Just need to swap the name in https://github.com/middleman/middleman-guides/settings with the changes in this PR.
Closes https://github.com/middleman/middleman-guides/issues/649

Change repo name to middlemanapp.com

---

Gemfile
Gemfile.lock

Neat 2.0 was recently released and has major breaking changes from the 1.x release cycle. This locks Neat into 1.x releases until we upgrade.

Lock Neat gem into 1.x releases

---

Gemfile
Gemfile.lock
config.rb
source/partials/_hero.erb
source/stylesheets/modules/landing/_hero.scss

The badge is an external resource and adds an extra request to the page.
It is also inaccessible because the version number is within a `img`,
where assistive technology cannot access it.
This commit uses the `middleman-data_source` gem to mount remote JSON
as local data from the RubyGems API, which we can pull the latest
version number from.
See: https://github.com/stevenosloan/middleman-data_source
---
Note, since this is a statically compiled site, the one downfall with this approach is that when a new gem version is released, the site won’t know about it. We can setup a [GitHub webhook](https://github.com/middleman/middleman-guides/settings/hooks) to send when a new release is published, and for Netlify to listen for that webhook and kick off a new build/deploy: …

Swap Gemfury badge for static version number

---

package.json

The heading `id`’s and anchor links for the docs are not being generated. Reverting `anchor-js` back down to 2.1.0 appears to resolve the issue.

Fix heading anchors

---

Gemfile
Gemfile.lock
bin/proof

html-proofer will check the built site for broken links, among a few other HTML errors.
I’ve been using it to fix a bunch of broken links that we had (e.g. https://github.com/middleman/middlemanapp.com/commit/7e12a6eb2d44cd5cdb3ff9f3ffd4a68f2df6cb95, https://github.com/middleman/middlemanapp.com/commit/60a9361f5e74f15c38fc25fd5a2f6d1ece118dbb, https://github.com/middleman/middlemanapp.com/commit/7fbcdff2f882b3a67ccf2e622f3603ab3e825a19). Having this script makes it _really easy_ to run.
I originally thought to have this as a step in Travis CI, but it broke the build so many time with false positives that I think we should leave it out and just run it manually from time to time.

Add a script to run html-proofer

---

source/localizable/basics/frontmatter.html.markdown

The frontmatter documentation lists `ignore: true` as a way to remove a page. The actual frontmatter setting to hide pages apparently is `ignored: true`. This pull request adjusts the documentation accordingly.

Changes `ignore` to actually working `ignored` config

---

Gemfile
Gemfile.lock
config.rb
helpers/guide_helpers.rb
locales/en.yml
locales/jp.yml
source/partials/_documentation_nav.erb
source/stylesheets/modules/_documentation-nav.scss

~~WIP:~~ The `active_link_to` helper is not currently working, ~~and is still not working after these changes. It outputs the link, but no class. Help on figuring that out is greatly appreciated.~~ Update: all good now.
This PR injects and styles off of an `aria-current` attribute instead of a class.
See: http://tink.uk/using-the-aria-current-attribute/

Refactor `active_link_to` helper

---

source/localizable/advanced/project-templates.html.markdown

- Wrap lines at 80 characters
- Easier to parse and allows us to comment more directly, line-by-line in GitHub PR's
- Use reference style links

Markdown style

---

source/localizable/basics/build-and-deploy.html.markdown

The `NO_CONTRACTS` variable was not documented but it's useful
to reduce build times.
Documentation was added after a brief discussion in
https://github.com/middleman/middleman/issues/2094

Document how to disable contracts

---

source/localizable/basics/blogging.html.markdown

Reference style link for blog_calendar spelled incorrectly as
blog_caldendar. Hyperlink is not being rendered. Fix the spelling in the
body text so the refernce style link can be matched and the hyperlink
displayed.

Spell blog_calendar correctly in basics/blogging

---

source/localizable/basics/layouts.html.markdown

Add note clarifying need for `=` with Haml/Slim.

---

source/localizable/basics/redirects.html.markdown

The existing documentation is unclear on what to do with the example redirect. Users might interpret it as something to run from the command line, or to be added at the top of the file to be redirected. This small change clarifies that redirects must be specified in `config.rb`

Specify where to apply redirects

---

data/sites.yml

We just published the new version of the official website for [Oswald Labs](https://oswaldlabs.com). The source is available on GitHub. Would love to see it in your list. 😄

Add oswaldlabs.com

---

source/localizable/advanced/file-size-optimization.html.markdown
source/localizable/advanced/file-size-optimization.jp.html.markdown

`srcset` is now generally supported: https://caniuse.com/#feat=srcset

Remove mention of `srcset` browser support

---

source/localizable/basics/helper-methods.html.markdown

The previous documentation had me putting my helper modules in `lib` first, and only if I kept reading I'd discover there was a better way of doing things and I'd have to move things around.
With this change, we make things easy up front, and if people have needs that go outside the easy path they can keep reading.

Highlight the easy way of creating helpers

---

data/sites.yml

We are using Middleman to generate the docs at OpenProject. Thanks to all contributors of this wonderful project. We really appreciate your effort. We are currently migrating also our website from WordPress to static website generated with Middleman.

Adding https://docs.openproject.org

---

source/localizable/advanced/external-pipeline.html.markdown
source/localizable/advanced/external-pipeline.jp.html.markdown

The address of the broccoli website changed. I updated the link in the external assets pipeline document.

fix: link to broccoli project
